# Generated by Django 2.0 on 2017-12-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='partial_total',
            new_name='total',
        ),
    ]
